# Generated by Django 2.2.10 on 2021-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlalgorithm',
            name='parent_endpoint',
        ),
        migrations.RemoveField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='mlrequest',
            name='parent_mlalgorithm',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ID',
        ),
        migrations.AddField(
            model_name='project',
            name='Title',
            field=models.CharField(default='project', max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
       
        migrations.DeleteModel(
            name='MLAlgorithmStatus',
        ),
        migrations.DeleteModel(
            name='MLRequest',
        ),
    ]
